# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-AllOrNothing
version:      0.09
version_from: lib/Crypt/AllOrNothing.pm
installdirs:  site
requires:
    Carp:                          0
    Crypt::AllOrNothing::Util:     0
    Crypt::OpenSSL::AES:           0
    Crypt::Random:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
